In [1]:
from transformers import TFBertForMaskedLM
from transformers import AutoTokenizer

In [3]:
# 버트는 사전훈련된 모델이다. 원하는 종류의 모델 이름으로 분류해서 로드한다.
# 또한 그 이름에 맞는 즉 그 모델에 맞는 또는 그 모델을 만들때 사용했던 토크나이저를 로드한다.
model = TFBertForMaskedLM.from_pretrained('bert-large-uncased', from_pt=True)
tokenizer = AutoTokenizer.from_pretrained("bert-large-uncased")

All PyTorch model weights were used when initializing TFBertForMaskedLM.

All the weights of TFBertForMaskedLM were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForMaskedLM for predictions without further training.


In [ ]:
# 주어진 문장에 대한 인코딩 테스트
inputs = tokenizer('Soccer is a really fun [MASK].', return_tensors='tf')
print(inputs) # 어떤 형태인지 볼려고 한번 찍어봄
print(inputs['input_ids'])

{'input_ids': <tf.Tensor: shape=(1, 9), dtype=int32, numpy=array([[ 101, 4715, 2003, 1037, 2428, 4569,  103, 1012,  102]])>, 'token_type_ids': <tf.Tensor: shape=(1, 9), dtype=int32, numpy=array([[0, 0, 0, 0, 0, 0, 0, 0, 0]])>, 'attention_mask': <tf.Tensor: shape=(1, 9), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1, 1, 1, 1]])>}
tf.Tensor([[ 101 4715 2003 1037 2428 4569  103 1012  102]], shape=(1, 9), dtype=int32)


In [7]:
# 어텐션 마스크 확인. 현재는 패딩을 진행하지 않았기 때문에 전부 1이겠지
print(inputs['attention_mask'])

tf.Tensor([[1 1 1 1 1 1 1 1 1]], shape=(1, 9), dtype=int32)


In [8]:
# 버트 역시 트랜스포머 기반이다보니 transformes 패키지에는 다양한 기능을 가긴 라이브러리가 포함되어 있다
# FillMaskPipeline 역시 모델과 토큰나이저를 지정하면 mask값을 구해준다.

from transformers import FillMaskPipeline
pip = FillMaskPipeline(model=model, tokenizer=tokenizer)


TensorFlow and JAX classes are deprecated and will be removed in Transformers v5. We recommend migrating to PyTorch classes or pinning your version of Transformers.
Device set to use 0


In [11]:
# mask에 올 단어를 상위 5개를 보여준다.
pip('Soccer is a really fun [MASK].')

[{'score': 0.7621216177940369,
  'token': 4368,
  'token_str': 'sport',
  'sequence': 'soccer is a really fun sport.'},
 {'score': 0.20342311263084412,
  'token': 2208,
  'token_str': 'game',
  'sequence': 'soccer is a really fun game.'},
 {'score': 0.01220872811973095,
  'token': 2518,
  'token_str': 'thing',
  'sequence': 'soccer is a really fun thing.'},
 {'score': 0.001863053534179926,
  'token': 4023,
  'token_str': 'activity',
  'sequence': 'soccer is a really fun activity.'},
 {'score': 0.0013355057453736663,
  'token': 2492,
  'token_str': 'field',
  'sequence': 'soccer is a really fun field.'}]

In [12]:
pip('The Avengers is a really fun [MASK].')

[{'score': 0.25629115104675293,
  'token': 2265,
  'token_str': 'show',
  'sequence': 'the avengers is a really fun show.'},
 {'score': 0.1728418618440628,
  'token': 3185,
  'token_str': 'movie',
  'sequence': 'the avengers is a really fun movie.'},
 {'score': 0.11107777059078217,
  'token': 2466,
  'token_str': 'story',
  'sequence': 'the avengers is a really fun story.'},
 {'score': 0.07249009609222412,
  'token': 2186,
  'token_str': 'series',
  'sequence': 'the avengers is a really fun series.'},
 {'score': 0.07046662271022797,
  'token': 2143,
  'token_str': 'film',
  'sequence': 'the avengers is a really fun film.'}]

In [13]:
pip('I went to [MASK] this morning.')

[{'score': 0.35730797052383423,
  'token': 2147,
  'token_str': 'work',
  'sequence': 'i went to work this morning.'},
 {'score': 0.2330450713634491,
  'token': 2793,
  'token_str': 'bed',
  'sequence': 'i went to bed this morning.'},
 {'score': 0.1284506618976593,
  'token': 2082,
  'token_str': 'school',
  'sequence': 'i went to school this morning.'},
 {'score': 0.06230601668357849,
  'token': 3637,
  'token_str': 'sleep',
  'sequence': 'i went to sleep this morning.'},
 {'score': 0.046952664852142334,
  'token': 2465,
  'token_str': 'class',
  'sequence': 'i went to class this morning.'}]