In [12]:
import os
os.chdir(r"c:\projects\PY_MLE")

import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [13]:
sentences = ['nice great best amazing', 'stop lies', 'pitiful nerd', 'excellent work', 'supreme quality', 'bad', 'highly respectable']
y_train = [1, 0, 0, 1, 1, 0, 1]

In [14]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)
vocab_size = len(tokenizer.word_index) + 1
print("vocab_size:{}".format(vocab_size))

vocab_size:16


In [15]:
x_encoded = tokenizer.texts_to_sequences(sentences)
x_encoded

[[1, 2, 3, 4], [5, 6], [7, 8], [9, 10], [11, 12], [13], [14, 15]]

In [16]:
max_len = max(len(word) for word in x_encoded)
print("max_len:{}".format(max_len))

max_len:4


In [17]:
x_train = pad_sequences(x_encoded, maxlen=max_len)
y_train = np.array(y_train)
print(x_train)
print(y_train)

[[ 1  2  3  4]
 [ 0  0  5  6]
 [ 0  0  7  8]
 [ 0  0  9 10]
 [ 0  0 11 12]
 [ 0  0  0 13]
 [ 0  0 14 15]]
[1 0 0 1 1 0 1]


In [18]:
# 파일을 다운로드 받아서 불어왔더 치고. 시간이 너무 많이 걸림
embedding_dict = dict()
f = open('glove.6B.50d.txt', encoding='utf8') # 차원이 100은 파일이 깨졌나 보네. 잘 안열리네

for line in f:
    word_vector = line.split()
    word = word_vector[0] # 구조가 이렇게 되어 있다. 맨앞이 단어이다

    word_vector_arr = np.array(word_vector[1:], dtype='float32')
    embedding_dict[word] = word_vector_arr
f.close()

In [19]:
print("embedding vector: {}".format(len(embedding_dict)))

embedding vector: 400000


In [20]:
print(embedding_dict['respectable'])
print('벡터의 차원수:{}'.format(len(embedding_dict['respectable'])))

[-0.73561  -0.35295   0.17907  -0.93009   1.5901   -0.20534  -0.17829
  0.13656  -0.33916   0.69966  -0.42162  -1.1377    0.2608    0.099557
  0.18591  -0.81209   0.36996  -0.099477 -0.24003  -0.16256  -0.21501
 -0.038879  0.00816   0.3083    0.42441   0.072954 -0.96597  -0.19876
  0.3843    0.44995   1.3365    0.39146   0.81936   0.19135   0.48073
 -0.15956   0.037837  1.1447   -0.62182  -1.0824   -0.16087  -0.75431
  0.017611  0.54504  -0.83774  -0.14587  -0.22146   0.31283   0.70472
  0.47657 ]
벡터의 차원수:50


In [23]:
embedding_matrix = np.zeros((vocab_size, 50))
print(embedding_matrix)
print("embedding_matrix shape:{}".format(embedding_matrix.shape))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [24]:
print(tokenizer.word_index.items())

dict_items([('nice', 1), ('great', 2), ('best', 3), ('amazing', 4), ('stop', 5), ('lies', 6), ('pitiful', 7), ('nerd', 8), ('excellent', 9), ('work', 10), ('supreme', 11), ('quality', 12), ('bad', 13), ('highly', 14), ('respectable', 15)])


In [26]:
print('great mapping:{}'.format(tokenizer.word_index['great']))
print(embedding_dict['great'])

great mapping:2
[-0.026567  1.3357   -1.028    -0.3729    0.52012  -0.12699  -0.35433
  0.37824  -0.29716   0.093894 -0.034122  0.92961  -0.14023  -0.63299
  0.020801 -0.21533   0.96923   0.47654  -1.0039   -0.24013  -0.36325
 -0.004757 -0.5148   -0.4626    1.2447   -1.8316   -1.5581   -0.37465
  0.53362   0.20883   3.2209    0.64549   0.37438  -0.17657  -0.024164
  0.33786  -0.419     0.40081  -0.11449   0.051232 -0.15205   0.29855
 -0.44052   0.11089  -0.24633   0.66251  -0.26949  -0.49658  -0.41618
 -0.2549  ]


In [27]:
# 사전임베딩된 백터를 넣어준다.
for word, index in tokenizer.word_index.items():

    vector_value = embedding_dict.get(word)
    if vector_value is not None:
        embedding_matrix[index] = vector_value

In [30]:
embedding_matrix[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, Flatten

output_dim = 50

model = Sequential(
    [
        Embedding(vocab_size, output_dim=output_dim, weights=[embedding_matrix], input_length=max_len, trainable=False),
        Flatten(),
        Dense(1, activation='sigmoid')
    ]
)
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
model.fit(x_train, y_train, epochs=100, verbose=2)



Epoch 1/100


1/1 - 0s - loss: 0.9061 - acc: 0.1429 - 475ms/epoch - 475ms/step
Epoch 2/100
1/1 - 0s - loss: 0.8902 - acc: 0.2857 - 4ms/epoch - 4ms/step
Epoch 3/100
1/1 - 0s - loss: 0.8747 - acc: 0.2857 - 3ms/epoch - 3ms/step
Epoch 4/100
1/1 - 0s - loss: 0.8595 - acc: 0.2857 - 5ms/epoch - 5ms/step
Epoch 5/100
1/1 - 0s - loss: 0.8447 - acc: 0.2857 - 4ms/epoch - 4ms/step
Epoch 6/100
1/1 - 0s - loss: 0.8302 - acc: 0.2857 - 3ms/epoch - 3ms/step
Epoch 7/100
1/1 - 0s - loss: 0.8161 - acc: 0.4286 - 2ms/epoch - 2ms/step
Epoch 8/100
1/1 - 0s - loss: 0.8024 - acc: 0.4286 - 4ms/epoch - 4ms/step
Epoch 9/100
1/1 - 0s - loss: 0.7890 - acc: 0.4286 - 3ms/epoch - 3ms/step
Epoch 10/100
1/1 - 0s - loss: 0.7759 - acc: 0.4286 - 3ms/epoch - 3ms/step
Epoch 11/100
1/1 - 0s - loss: 0.7632 - acc: 0.5714 - 3ms/epoch - 3ms/step
Epoch 12/100
1/1 - 0s - loss: 0.7509 - acc: 0.5714 - 3ms/epoch - 3ms/step
Epoch 13/100
1/1 - 0s - loss: 0.7389 - acc: 0.5714 - 3ms/epoch - 3ms/step
Epoch 14/100
1/1 - 0s - loss: 0.7272 - 

In [37]:
# 최종가중치 구하기
embedding_matrix_weight = model.layers[0].get_weights()
print(len(embedding_matrix_weight[0]))
print(embedding_matrix_weight)

16
[array([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
       [ 2.0189e-01,  8.0606e-01, -1.1281e+00, -5.9593e-01,  5.2756e-01,
        -4.7690e-01, -5.2640e-01,  1.4526e-01, -8.6087e-01,  5.6199e-01,
        -4.3708e-01, -1.6586e-01, -2.3328e-01, -2.1726e-01,  5.2114e-01,
         6.2307e-02,  5.5115e-01, -1.8002e-01,