텐서플로우에는 많은 데이터셋을 제공한다.
데이터셋에 뭐가 있는지 조회

In [ ]:
import tensorflow as tf
from tensorflow.data import Dataset
import tensorflow_datasets as tfds
import numpy as np

builders= tfds.list_builders()
print(builders)
print(len(builders))

데이터를 불러올때 with_info=True를 해주는게 중요하네.
갖가지 정보를 조회하기 위해

In [ ]:
data, info = tfds.load('mnist', with_info=True)
print(info)
train_data, test_data = data['train'], data['test']
print(train_data)

tf.data에는 텐서플로우 데이터를 다룰수 있는 많은 함수들이 포함되어 있음
우리가 생성한 모델에 데이터를 넣기 위해서는 tf.data.Dataset 형태로 변환해야 한다.

from_tensors은 하나의 텐서를 생성한다.

In [ ]:
a = tf.data.Dataset.from_tensors(tf.constant([0,1,2,3,4]))
print(a)

from_tensor_slices 얘가 유용할 듯 여러개의 텐서를 한꺼번에 만들어 낸다.

In [25]:
a = tf.data.Dataset.from_tensor_slices([10,20,30,40,50,60])
b = tf.data.Dataset.from_tensor_slices(tf.random.uniform([4,2]))
print(a)
print(b)
for item in a:
    print(item)
for item in b:
    print(item)

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>
<_TensorSliceDataset element_spec=TensorSpec(shape=(2,), dtype=tf.float32, name=None)>
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(20, shape=(), dtype=int32)
tf.Tensor(30, shape=(), dtype=int32)
tf.Tensor(40, shape=(), dtype=int32)
tf.Tensor(50, shape=(), dtype=int32)
tf.Tensor(60, shape=(), dtype=int32)
tf.Tensor([0.97088206 0.19443989], shape=(2,), dtype=float32)
tf.Tensor([0.07403088 0.24381316], shape=(2,), dtype=float32)
tf.Tensor([0.3587433  0.25390136], shape=(2,), dtype=float32)
tf.Tensor([0.18227279 0.67236185], shape=(2,), dtype=float32)


batch, repeat
batch: 자료를 끊는다. drop_remainder=True이면 나머지는 버린다. 개수가 안되니까
repeat: 텐서를 반복한다.
아래와 같은 예제에서 1~10까지 텐서를 3번 반복하면 1,...10,1....10,1...10인데 이것을 7단위로 끊는다.

In [24]:
a = tf.data.Dataset.from_tensor_slices(np.arange(10))
b = a.repeat(3).batch(7)
for item in b:
    print(item)

print()

a = tf.data.Dataset.from_tensor_slices(np.arange(10))
b = a.repeat(3).batch(7, drop_remainder=True) 
for item in b:
    print(item)

tf.Tensor([0 1 2 3 4 5 6], shape=(7,), dtype=int32)
tf.Tensor([7 8 9 0 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([4 5 6 7 8 9 0], shape=(7,), dtype=int32)
tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int32)
tf.Tensor([8 9], shape=(2,), dtype=int32)

tf.Tensor([0 1 2 3 4 5 6], shape=(7,), dtype=int32)
tf.Tensor([7 8 9 0 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([4 5 6 7 8 9 0], shape=(7,), dtype=int32)
tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int32)


map. filter
기존 파이썬과 동일 함
또는 원하는 형태로 데이터셋 형태로 가져 올 수 있다.

In [ ]:
dataset = Dataset.range(1,6)
dataset = dataset.map(lambda x: x * 2)
list(dataset.as_numpy_iterator())

In [ ]:
elements = [(1,'one'),(2,'two'),(3,'three')]
dataset = Dataset.from_generator(lambda: elements, (tf.int32, tf.string))

result = dataset.map(lambda x_int, y_str: x_int)
list(result.as_numpy_iterator())

shuffle, take
섞고, 가져오기

In [ ]:
data, info = tfds.load('imdb_reviews', with_info=True)
train_data = data['train']
train_data = train_data.batch(5).shuffle(5).take(2) # shuffle(5)에서 5는 그냥 버퍼사이즈
for data in train_data:
    print(data)

get_next 다음텐서의 값을 순차적으로 가져오기

In [ ]:
dataset = Dataset.range(2)
iterater = iter(dataset)
print(dataset)
print(iterater.get_next())
print(iterater.get_next())


In [45]:
dataset = Dataset.from_tensor_slices(np.arange(1,10).reshape(3,3))
it = iter(dataset)

it.get_next()
it.get_next()
it.get_next()



<tf.Tensor: shape=(3,), dtype=int32, numpy=array([7, 8, 9])>

In [54]:
dataset = Dataset.from_tensor_slices(np.arange(1,10).reshape(3,3))
it = iter(dataset)

next(it).numpy()


array([1, 2, 3])